// frontend/src/modules/gameplay/views/RewardsPage.vue
<template>
  <div class="page-container">
    <!-- 退出按钮 -->
    <button
      @click="handleLogout"
      class="fixed top-4 right-4 z-50 p-2.5 rounded-xl bg-black/30 backdrop-blur-sm border border-white/10 hover:bg-white/20 transition-all duration-300 group"
      title="退出登录"
    >
      <svg class="w-5 h-5 text-white/70 group-hover:text-white transition-colors" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4"/>
        <polyline points="10 17 15 12 10 7"/>
        <line x1="15" y1="12" x2="3" y2="12"/>
      </svg>
    </button>
    <div class="max-w-4xl mx-auto">
      <router-link to="/plaza" class="inline-flex items-center gap-2 text-gray-400 hover:text-white mb-6 transition-colors">
        <span>←</span> 返回广场
      </router-link>

      <div class="text-center mb-10 animate-fade-in-up">
        <div class="relative inline-block">
          <div class="absolute -inset-6 bg-gradient-to-r from-yellow-500/10 via-orange-500/10 to-red-500/10 rounded-full blur-xl animate-pulse"></div>
          <h2 class="relative text-3xl font-black text-white mb-2">🎁 奖励中心</h2>
        </div>
        <p class="text-gray-400 mt-2">领取你的冒险奖励</p>
      </div>

      <div class="game-grid">
        <div
          v-for="(reward, i) in rewards"
          :key="reward.id"
          class="game-card p-6 text-center animate-fade-in-scale group relative overflow-hidden"
          :class="'game-card-glow-gold'"
          :style="{ animationDelay: (i * 0.1) + 's' }"
        >
          <div class="floating-particles">
            <span class="particle"></span><span class="particle"></span>
          </div>

          <div class="relative z-10">
            <div class="w-16 h-16 rounded-2xl bg-gradient-to-br from-yellow-500/20 to-orange-500/20 flex items-center justify-center text-4xl mx-auto mb-3 group-hover:scale-110 transition-transform duration-300">
              🎁
            </div>
            <h3 class="text-lg font-bold text-white mb-4">{{ reward.name }}</h3>

            <div class="space-y-2 text-sm mb-4">
              <div class="flex justify-between py-2 px-3 rounded-lg bg-white/5 border border-white/5">
                <span class="text-gray-400">💎 金币</span>
                <span class="text-yellow-400 font-bold">+{{ reward.coin_amount }}</span>
              </div>
              <div class="flex justify-between py-2 px-3 rounded-lg bg-white/5 border border-white/5">
                <span class="text-gray-400">⭐ 经验</span>
                <span class="text-blue-400 font-bold">+{{ reward.exp_amount }}</span>
              </div>
              <div class="flex justify-between py-2 px-3 rounded-lg bg-white/5 border border-white/5">
                <span class="text-gray-400">🐟 猫粮</span>
                <span class="text-orange-400 font-bold">+{{ reward.cat_food_amount }}</span>
              </div>
            </div>

            <button class="game-btn game-btn-gold w-full">
              🎁 领取奖励
            </button>
          </div>
        </div>

        <div v-if="rewards.length === 0" class="col-span-full game-card p-12 text-center">
          <div class="text-5xl mb-4">🎁</div>
          <p class="text-gray-400 text-lg">暂无可用奖励</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useUserStore } from '@/stores/user'
import { gameApi } from '@/api/game'

const router = useRouter()
const userStore = useUserStore()

async function handleLogout() {
  await userStore.logoutWithSave()
  router.push('/login')
}

const rewards = ref([])

onMounted(async () => {
  try {
    const res = await gameApi.listRewards()
    rewards.value = res || []
  } catch (e) {
    console.error('Failed to load rewards:', e)
  }
})
</script>

// frontend/src/components/RewardsPage.jsx
import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { rewardApi } from '../services/api'

function RewardsPage() {
  const [rewards, setRewards] = useState([])
  const [achievements, setAchievements] = useState([])
  const [claimedRewards, setClaimedRewards] = useState([])
  const navigate = useNavigate()

  useEffect(() => {
    const fetchData = async () => {
      try {
        const rewardsResponse = await rewardApi.getAll()
        setRewards(rewardsResponse.data)
        
        const achievementsResponse = await rewardApi.getAchievements()
        setAchievements(achievementsResponse.data)
      } catch (err) {
        console.error('Failed to fetch rewards:', err)
      }
    }
    fetchData()
  }, [])

  const handleClaimReward = async (rewardId) => {
    if (claimedRewards.includes(rewardId)) return
    
    try {
      const response = await rewardApi.claim(rewardId)
      alert(`领取成功！\n经验: ${response.data.rewards.exp}\n金币: ${response.data.rewards.coins}`)
      setClaimedRewards([...claimedRewards, rewardId])
    } catch (err) {
      console.error('Failed to claim reward:', err)
    }
  }

  return (
    <div className="min-h-screen">
      <div className="ui-overlay">
        <div className="absolute top-0 left-0 right-0 p-4 flex justify-between items-center bg-white/80 backdrop-blur-sm">
          <button onClick={() => navigate('/plaza')} className="btn-primary">返回广场</button>
          <h1 className="text-xl font-bold text-academic-purple">通关奖励</h1>
          <div className="w-20"></div>
        </div>
        
        <div className="absolute top-20 left-4 right-4 bottom-4">
          <div className="card-game mb-6">
            <h3 className="font-bold text-lg text-campus-blue mb-4 flex items-center gap-2">
              <span>🎁</span> 可领取奖励
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {rewards.map((reward) => (
                <div
                  key={reward.id}
                  className="p-4 bg-gradient-to-br from-yellow-50 to-orange-50 rounded-xl border border-yellow-200"
                >
                  <div className="flex justify-between items-start mb-2">
                    <h4 className="font-bold text-gray-800">{reward.name}</h4>
                    <span className="text-2xl">⭐</span>
                  </div>
                  
                  <div className="flex gap-4 mb-4">
                    {reward.exp_amount > 0 && (
                      <div className="flex items-center gap-1">
                        <span>⭐</span>
                        <span className="text-sm font-bold text-healing-green">{reward.exp_amount}</span>
                      </div>
                    )}
                    {reward.coin_amount > 0 && (
                      <div className="flex items-center gap-1">
                        <span>💰</span>
                        <span className="text-sm font-bold text-yellow-600">{reward.coin_amount}</span>
                      </div>
                    )}
                    {reward.cat_food_amount > 0 && (
                      <div className="flex items-center gap-1">
                        <span>🐟</span>
                        <span className="text-sm font-bold text-sakura">{reward.cat_food_amount}</span>
                      </div>
                    )}
                  </div>
                  
                  <button
                    onClick={() => handleClaimReward(reward.id)}
                    disabled={claimedRewards.includes(reward.id)}
                    className={`w-full py-2 rounded-lg font-semibold transition-all ${
                      claimedRewards.includes(reward.id)
                        ? 'bg-gray-300 text-gray-500 cursor-not-allowed'
                        : 'btn-game'
                    }`}
                  >
                    {claimedRewards.includes(reward.id) ? '已领取' : '领取奖励'}
                  </button>
                </div>
              ))}
            </div>
          </div>
          
          <div className="card-game">
            <h3 className="font-bold text-lg text-academic-purple mb-4 flex items-center gap-2">
              <span>🏆</span> 成就系统
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {achievements.map((achievement) => (
                <div
                  key={achievement.id}
                  className={`p-4 rounded-xl border-2 transition-all ${
                    achievement.unlocked
                      ? 'bg-gradient-to-br from-yellow-50 to-amber-50 border-yellow-400'
                      : 'bg-gray-50 border-gray-200'
                  }`}
                >
                  <div className="flex items-center gap-3">
                    <div className={`text-3xl ${achievement.unlocked ? '' : 'opacity-30'}`}>
                      {achievement.unlocked ? '🏅' : '🔒'}
                    </div>
                    <div>
                      <h4 className={`font-bold ${achievement.unlocked ? 'text-gray-800' : 'text-gray-400'}`}>
                        {achievement.name}
                      </h4>
                      <p className={`text-xs ${achievement.unlocked ? 'text-gray-600' : 'text-gray-400'}`}>
                        {achievement.description}
                      </p>
                    </div>
                  </div>
                  {achievement.unlocked && (
                    <div className="mt-3 flex items-center justify-center gap-2 text-xs text-yellow-600 bg-yellow-100 rounded-full py-1 px-3">
                      <span>✨</span>
                      <span>已解锁</span>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
      
      <div className="game-container">
        <div className="phaser-game bg-gradient-to-b from-yellow-200 to-orange-300">
          <div className="absolute inset-0 flex items-center justify-center">
            <div className="text-center">
              <div className="text-6xl mb-4">🎁</div>
              <h2 className="text-2xl font-bold text-white">奖励系统</h2>
              <p className="text-gray-700 mt-2">领取通关奖励和成就</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default RewardsPage
